blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/microsproject/micros/blob/main/README.md
    about: Check the documentation for common questions
  - name: 💬 Discussions
    url: https://github.com/microsproject/micros/discussions
    about: Ask questions and discuss ideas with the community